language: go
go:
  - 1.3.3
install: go get -v -t ./...
script: PG_DB="user=postgres sslmode=disable" go test -v ./...
notifications:
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email:
    recipients:
      - coda.hale@gmail.com
